name: Test docker image build
on:
  push:

permissions:
  contents: read

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ddnet-insta/docker/Dockerfile
          push: false
